### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by yunfour** [elover/gulp-cmd#1]
使用时报错，说有一个对象找不到write方法，是我的配置问题，还是我的姿势不对，下面是我的配置和报错信息
## gulp.js的代码：

``` js
var gulp = require('gulp');
var cmd = require('gulp-cmd');

gulp.task('cmd', function() {

    return gulp.src('src/js/cmd/test/test.js')
               .pipe(cmd())
               .pipe(gulp.task('build/js/cmd/test'));
});

gulp.task('default', ['cmd']);
```
## 报错信息

[14:57:05] gulp-cmd error: Object #<Gulp> has no method 'write'
TypeError: Object #<Gulp> has no method 'write'
    at write (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:623:24)
    at flow (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_
stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:448
:10)
    at emitReadable (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:444:
5)
    at readableAddChunk (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:
187:9)
    at DestroyableTransform.Readable.push (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_s
tream_readable.js:149:10)
    at DestroyableTransform.Transform.push (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_
stream_transform.js:145:32)
    at afterTransform (E:\gulp\node_modules\gulp-cmd\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:1
01:12)

**Comment by elover** [comment]
请确保依赖都加载好了,我用了很久，都没出现问题的
